version: 0.2

phases:
  install:
    commands:
    - npm install 
    
  build:
    commands:
    - npm run build:ci

artifacts:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
    
base-directory: 'dist/automotive-agendamiento'    
discard-paths: yes


